# Generated by Django 2.1.7 on 2019-03-19 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(verbose_name='Comment Date')),
                ('review', models.TextField(max_length=250)),
                ('ratings', models.CharField(choices=[('5', '*****'), ('4', '****'), ('3', '***'), ('2', '**'), ('1', '*'), ('0', '')], default='5', max_length=1)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Opu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('comments', models.ManyToManyField(to='main_app.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Readrr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bio', models.TextField(max_length=250)),
                ('joined', models.DateField(verbose_name='Joined Date')),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Writrr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('bio', models.TextField(max_length=250)),
                ('joined', models.DateField(verbose_name='Joined Date')),
                ('readrrs', models.ManyToManyField(to='main_app.Readrr')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='opu',
            name='writrr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Writrr'),
        ),
        migrations.AddField(
            model_name='comment',
            name='readrr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Readrr'),
        ),
        migrations.AddField(
            model_name='comment',
            name='writrr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Writrr'),
        ),
    ]
